// GENERATED by scripts/download-photos.mjs, then hand-curated.
// Edit `category` and `alt` freely; dimensions are canonical (from sharp).

export type PhotoCategory = 'folks' | 'branding' | 'wild' | 'wander'

export interface Photo {
  id: string
  src: string
  thumb: string
  w: number
  h: number
  /** aspect ratio, w / h */
  ar: number
  category: PhotoCategory
  alt: string
  sourcePage: string
}

export const photos: Photo[] = [
  { id: '003-dsc-8066-1', src: '/photos/web/003-dsc-8066-1.webp', thumb: '/photos/thumb/003-dsc-8066-1.webp', w: 1600, h: 1068, ar: 1.4981, category: 'wild', alt: "Saddle up in the barn", sourcePage: '/' },
  { id: '004-dsc-9099-copy', src: '/photos/web/004-dsc-9099-copy.webp', thumb: '/photos/thumb/004-dsc-9099-copy.webp', w: 1271, h: 1600, ar: 0.7944, category: 'wild', alt: "Splashing through the shallows", sourcePage: '/' },
  { id: '005-dsc-7297', src: '/photos/web/005-dsc-7297.webp', thumb: '/photos/thumb/005-dsc-7297.webp', w: 1284, h: 1600, ar: 0.8025, category: 'folks', alt: "Cowgirl and her horse", sourcePage: '/' },
  { id: '006-dsc-8962-2-copy', src: '/photos/web/006-dsc-8962-2-copy.webp', thumb: '/photos/thumb/006-dsc-8962-2-copy.webp', w: 1600, h: 1576, ar: 1.0152, category: 'wild', alt: "Crossing the creek on horseback", sourcePage: '/' },
  { id: '007-dsc-8749', src: '/photos/web/007-dsc-8749.webp', thumb: '/photos/thumb/007-dsc-8749.webp', w: 1067, h: 1600, ar: 0.6669, category: 'folks', alt: "Silhouette in the barn door", sourcePage: '/' },
  { id: '008-img-2024', src: '/photos/web/008-img-2024.webp', thumb: '/photos/thumb/008-img-2024.webp', w: 1067, h: 1600, ar: 0.6669, category: 'folks', alt: "Last light vows at the lake", sourcePage: '/' },
  { id: '009-dsc-4183', src: '/photos/web/009-dsc-4183.webp', thumb: '/photos/thumb/009-dsc-4183.webp', w: 1600, h: 1067, ar: 1.4995, category: 'wild', alt: "Behind the rodeo chutes", sourcePage: '/' },
  { id: '010-dsc-7552', src: '/photos/web/010-dsc-7552.webp', thumb: '/photos/thumb/010-dsc-7552.webp', w: 1332, h: 1600, ar: 0.8325, category: 'folks', alt: "At-home session, mid laugh", sourcePage: '/' },
  { id: '011-dsc-0404', src: '/photos/web/011-dsc-0404.webp', thumb: '/photos/thumb/011-dsc-0404.webp', w: 1067, h: 1600, ar: 0.6669, category: 'folks', alt: "Red boots at the bar", sourcePage: '/' },
  { id: '012-dsc-2872', src: '/photos/web/012-dsc-2872.webp', thumb: '/photos/thumb/012-dsc-2872.webp', w: 1173, h: 1274, ar: 0.9207, category: 'folks', alt: "Portrait in low light", sourcePage: '/' },
  { id: '013-dsc-0101', src: '/photos/web/013-dsc-0101.webp', thumb: '/photos/thumb/013-dsc-0101.webp', w: 1067, h: 1600, ar: 0.6669, category: 'branding', alt: "Pie and coffee at the diner", sourcePage: '/' },
  { id: '014-dsc-0905', src: '/photos/web/014-dsc-0905.webp', thumb: '/photos/thumb/014-dsc-0905.webp', w: 1067, h: 1600, ar: 0.6669, category: 'folks', alt: "Wading in, dress and all", sourcePage: '/' },
  { id: '015-dsc-1890', src: '/photos/web/015-dsc-1890.webp', thumb: '/photos/thumb/015-dsc-1890.webp', w: 1600, h: 1167, ar: 1.371, category: 'folks', alt: "Floating portrait", sourcePage: '/' },
  { id: '016-dsc-2936', src: '/photos/web/016-dsc-2936.webp', thumb: '/photos/thumb/016-dsc-2936.webp', w: 1600, h: 1067, ar: 1.4995, category: 'folks', alt: "Portrait in the dunes", sourcePage: '/' },
  { id: '017-dsc-0627', src: '/photos/web/017-dsc-0627.webp', thumb: '/photos/thumb/017-dsc-0627.webp', w: 1600, h: 1067, ar: 1.4995, category: 'folks', alt: "White dress on the dunes", sourcePage: '/' },
  { id: '018-dsc-6026-1', src: '/photos/web/018-dsc-6026-1.webp', thumb: '/photos/thumb/018-dsc-6026-1.webp', w: 1600, h: 1068, ar: 1.4981, category: 'wander', alt: "Smoke over the campfire", sourcePage: '/' },
  { id: '019-img-2710-2', src: '/photos/web/019-img-2710-2.webp', thumb: '/photos/thumb/019-img-2710-2.webp', w: 1068, h: 1600, ar: 0.6675, category: 'folks', alt: "Cowboy and his dog at the cabin", sourcePage: '/' },
  { id: '020-dsc-4960-2', src: '/photos/web/020-dsc-4960-2.webp', thumb: '/photos/thumb/020-dsc-4960-2.webp', w: 1600, h: 1067, ar: 1.4995, category: 'wild', alt: "Horses on the sand", sourcePage: '/' },
  { id: '021-img-2704-2', src: '/photos/web/021-img-2704-2.webp', thumb: '/photos/thumb/021-img-2704-2.webp', w: 1068, h: 1600, ar: 0.6675, category: 'folks', alt: "Bride in the ruins", sourcePage: '/' },
  { id: '022-dsc-0076-1', src: '/photos/web/022-dsc-0076-1.webp', thumb: '/photos/thumb/022-dsc-0076-1.webp', w: 1600, h: 1068, ar: 1.4981, category: 'folks', alt: "Backpacks and a kiss in the meadow", sourcePage: '/' },
  { id: '023-dsc-6642-1-2', src: '/photos/web/023-dsc-6642-1-2.webp', thumb: '/photos/thumb/023-dsc-6642-1-2.webp', w: 1600, h: 1068, ar: 1.4981, category: 'wild', alt: "Moving the herd", sourcePage: '/' },
  { id: '024-dsc-3716-1', src: '/photos/web/024-dsc-3716-1.webp', thumb: '/photos/thumb/024-dsc-3716-1.webp', w: 1600, h: 1245, ar: 1.2851, category: 'folks', alt: "Bouquet under a felt hat", sourcePage: '/' },
  { id: '025-img-2718', src: '/photos/web/025-img-2718.webp', thumb: '/photos/thumb/025-img-2718.webp', w: 1077, h: 1600, ar: 0.6731, category: 'wild', alt: "Pink shirt, dusty arena", sourcePage: '/' },
  { id: '026-dsc-1738-1', src: '/photos/web/026-dsc-1738-1.webp', thumb: '/photos/thumb/026-dsc-1738-1.webp', w: 1600, h: 1068, ar: 1.4981, category: 'folks', alt: "Cake and the girls", sourcePage: '/' },
  { id: '027-dsc-4900-1', src: '/photos/web/027-dsc-4900-1.webp', thumb: '/photos/thumb/027-dsc-4900-1.webp', w: 1600, h: 1034, ar: 1.5474, category: 'folks', alt: "Three generations, one hug", sourcePage: '/' },
  { id: '028-dsc-8602-1', src: '/photos/web/028-dsc-8602-1.webp', thumb: '/photos/thumb/028-dsc-8602-1.webp', w: 1068, h: 1600, ar: 0.6675, category: 'folks', alt: "Porch light portrait", sourcePage: '/' },
  { id: '029-dsc-5993-1', src: '/photos/web/029-dsc-5993-1.webp', thumb: '/photos/thumb/029-dsc-5993-1.webp', w: 1294, h: 1600, ar: 0.8087, category: 'branding', alt: "The pour", sourcePage: '/' },
  { id: '030-dsc-6933-1', src: '/photos/web/030-dsc-6933-1.webp', thumb: '/photos/thumb/030-dsc-6933-1.webp', w: 1600, h: 1068, ar: 1.4981, category: 'branding', alt: "House bar, local dog", sourcePage: '/' },
  { id: '031-dsc-8034-1', src: '/photos/web/031-dsc-8034-1.webp', thumb: '/photos/thumb/031-dsc-8034-1.webp', w: 1600, h: 1067, ar: 1.4995, category: 'branding', alt: "Dinosaur painting in progress", sourcePage: '/' },
  { id: '032-dsc-7014-1', src: '/photos/web/032-dsc-7014-1.webp', thumb: '/photos/thumb/032-dsc-7014-1.webp', w: 1068, h: 1600, ar: 0.6675, category: 'branding', alt: "At the saddlery", sourcePage: '/' },
  { id: '033-dsc-7831-2-1', src: '/photos/web/033-dsc-7831-2-1.webp', thumb: '/photos/thumb/033-dsc-7831-2-1.webp', w: 1600, h: 1027, ar: 1.5579, category: 'folks', alt: "Pizza, but make it bridal", sourcePage: '/' },
  { id: '034-dsc-3095-1-2', src: '/photos/web/034-dsc-3095-1-2.webp', thumb: '/photos/thumb/034-dsc-3095-1-2.webp', w: 1068, h: 1600, ar: 0.6675, category: 'folks', alt: "Through the veil", sourcePage: '/' },
  { id: '035-dsc-7022-1', src: '/photos/web/035-dsc-7022-1.webp', thumb: '/photos/thumb/035-dsc-7022-1.webp', w: 1068, h: 1600, ar: 0.6675, category: 'wild', alt: "Rope out over the herd", sourcePage: '/' },
  { id: '036-dsc-9317-1', src: '/photos/web/036-dsc-9317-1.webp', thumb: '/photos/thumb/036-dsc-9317-1.webp', w: 1600, h: 1068, ar: 1.4981, category: 'folks', alt: "Wildflower elopement", sourcePage: '/' },
  { id: '037-img-2714', src: '/photos/web/037-img-2714.webp', thumb: '/photos/thumb/037-img-2714.webp', w: 1600, h: 1068, ar: 1.4981, category: 'folks', alt: "Hat to hat", sourcePage: '/' },
  { id: '038-img-2715', src: '/photos/web/038-img-2715.webp', thumb: '/photos/thumb/038-img-2715.webp', w: 1600, h: 1086, ar: 1.4733, category: 'wild', alt: "Neck and neck in the arena", sourcePage: '/' },
  { id: '039-img-2711', src: '/photos/web/039-img-2711.webp', thumb: '/photos/thumb/039-img-2711.webp', w: 1600, h: 1254, ar: 1.2759, category: 'folks', alt: "Tattoos and tulle", sourcePage: '/' },
  { id: '040-dsc-0041-1', src: '/photos/web/040-dsc-0041-1.webp', thumb: '/photos/thumb/040-dsc-0041-1.webp', w: 1100, h: 1600, ar: 0.6875, category: 'folks', alt: "Getting ready, heels first", sourcePage: '/' },
  { id: '041-dji-fly-20230827-063226-105-169314007455', src: '/photos/web/041-dji-fly-20230827-063226-105-169314007455.webp', thumb: '/photos/thumb/041-dji-fly-20230827-063226-105-169314007455.webp', w: 1600, h: 1200, ar: 1.3333, category: 'wander', alt: "Climber at sundown", sourcePage: '/' },
  { id: '042-dsc-0007-1-2', src: '/photos/web/042-dsc-0007-1-2.webp', thumb: '/photos/thumb/042-dsc-0007-1-2.webp', w: 1600, h: 1270, ar: 1.2598, category: 'folks', alt: "Carried across the creek, dog supervising", sourcePage: '/' },
  { id: '043-tempimage5rurk9', src: '/photos/web/043-tempimage5rurk9.webp', thumb: '/photos/thumb/043-tempimage5rurk9.webp', w: 1123, h: 1600, ar: 0.7019, category: 'folks', alt: "Boots under the dress", sourcePage: '/' },
  { id: '044-dsc-2399-1', src: '/photos/web/044-dsc-2399-1.webp', thumb: '/photos/thumb/044-dsc-2399-1.webp', w: 1600, h: 1068, ar: 1.4981, category: 'wild', alt: "Bronc at the rails", sourcePage: '/' },
  { id: '045-jpeg', src: '/photos/web/045-jpeg.webp', thumb: '/photos/thumb/045-jpeg.webp', w: 1176, h: 1600, ar: 0.735, category: 'wander', alt: "Roped into the redrock", sourcePage: '/' },
  { id: '046-img-2655', src: '/photos/web/046-img-2655.webp', thumb: '/photos/thumb/046-img-2655.webp', w: 1068, h: 1600, ar: 0.6675, category: 'folks', alt: "Snowy engagement", sourcePage: '/' },
  { id: '047-img-9865', src: '/photos/web/047-img-9865.webp', thumb: '/photos/thumb/047-img-9865.webp', w: 1373, h: 1600, ar: 0.8581, category: 'folks', alt: "The quiet hold", sourcePage: '/' },
  { id: '048-dsc-7200-1-2', src: '/photos/web/048-dsc-7200-1-2.webp', thumb: '/photos/thumb/048-dsc-7200-1-2.webp', w: 1366, h: 1600, ar: 0.8538, category: 'folks', alt: "The yes, on one knee", sourcePage: '/' },
  { id: '049-dsc-2218-1', src: '/photos/web/049-dsc-2218-1.webp', thumb: '/photos/thumb/049-dsc-2218-1.webp', w: 1600, h: 1067, ar: 1.4995, category: 'folks', alt: "Two hats on the open plain", sourcePage: '/' },
  { id: '050-dsc-2695-1', src: '/photos/web/050-dsc-2695-1.webp', thumb: '/photos/thumb/050-dsc-2695-1.webp', w: 1600, h: 1067, ar: 1.4995, category: 'folks', alt: "Wind, white dress, wild horses", sourcePage: '/' },
  { id: '051-img-6424', src: '/photos/web/051-img-6424.webp', thumb: '/photos/thumb/051-img-6424.webp', w: 1600, h: 1067, ar: 1.4995, category: 'folks', alt: "Just married in the redrocks", sourcePage: '/' },
  { id: '052-concert', src: '/photos/web/052-concert.webp', thumb: '/photos/thumb/052-concert.webp', w: 1600, h: 1067, ar: 1.4995, category: 'wander', alt: "Crowd surfing the encore", sourcePage: '/' },
  { id: '053-img-2712', src: '/photos/web/053-img-2712.webp', thumb: '/photos/thumb/053-img-2712.webp', w: 1600, h: 1068, ar: 1.4981, category: 'folks', alt: "Lamp-lit slow dance", sourcePage: '/' },
  { id: '054-img-2724', src: '/photos/web/054-img-2724.webp', thumb: '/photos/thumb/054-img-2724.webp', w: 1600, h: 1057, ar: 1.5137, category: 'folks', alt: "Upside down in tulle", sourcePage: '/' },
  { id: '055-img-2728', src: '/photos/web/055-img-2728.webp', thumb: '/photos/thumb/055-img-2728.webp', w: 1600, h: 1068, ar: 1.4981, category: 'folks', alt: "The bouquet, held close", sourcePage: '/' },
  { id: '056-img-2727', src: '/photos/web/056-img-2727.webp', thumb: '/photos/thumb/056-img-2727.webp', w: 1402, h: 1600, ar: 0.8762, category: 'folks', alt: "First look flowers", sourcePage: '/' },
  { id: '057-img-2723', src: '/photos/web/057-img-2723.webp', thumb: '/photos/thumb/057-img-2723.webp', w: 1600, h: 1139, ar: 1.4047, category: 'wander', alt: "Whiskey and a quiet booth", sourcePage: '/' },
  { id: '058-img-2712', src: '/photos/web/058-img-2712.webp', thumb: '/photos/thumb/058-img-2712.webp', w: 1600, h: 1068, ar: 1.4981, category: 'folks', alt: "Between the lamps", sourcePage: '/' },
  { id: '059-img-2713', src: '/photos/web/059-img-2713.webp', thumb: '/photos/thumb/059-img-2713.webp', w: 1068, h: 1600, ar: 0.6675, category: 'folks', alt: "Disco ball elopement", sourcePage: '/' },
  { id: '060-dsc-5777-1', src: '/photos/web/060-dsc-5777-1.webp', thumb: '/photos/thumb/060-dsc-5777-1.webp', w: 1600, h: 1068, ar: 1.4981, category: 'branding', alt: "Coffee in hand", sourcePage: '/' },
  { id: '061-dsc-1796-1', src: '/photos/web/061-dsc-1796-1.webp', thumb: '/photos/thumb/061-dsc-1796-1.webp', w: 1068, h: 1600, ar: 0.6675, category: 'folks', alt: "Winter light through the pines", sourcePage: '/' },
  { id: '062-dsc-7028-1', src: '/photos/web/062-dsc-7028-1.webp', thumb: '/photos/thumb/062-dsc-7028-1.webp', w: 1600, h: 1048, ar: 1.5267, category: 'branding', alt: "Hands at work in the kitchen", sourcePage: '/' },
  { id: '063-dsc-7981-1', src: '/photos/web/063-dsc-7981-1.webp', thumb: '/photos/thumb/063-dsc-7981-1.webp', w: 1600, h: 1231, ar: 1.2998, category: 'folks', alt: "Turquoise and a straw brim", sourcePage: '/' },
  { id: '064-dsc-3669-1', src: '/photos/web/064-dsc-3669-1.webp', thumb: '/photos/thumb/064-dsc-3669-1.webp', w: 1204, h: 1600, ar: 0.7525, category: 'wander', alt: "The strange table", sourcePage: '/' },
  { id: '065-img-2708', src: '/photos/web/065-img-2708.webp', thumb: '/photos/thumb/065-img-2708.webp', w: 1600, h: 1068, ar: 1.4981, category: 'branding', alt: "The workshop regulars", sourcePage: '/' },
  { id: '066-dsc-4819-1', src: '/photos/web/066-dsc-4819-1.webp', thumb: '/photos/thumb/066-dsc-4819-1.webp', w: 1600, h: 1068, ar: 1.4981, category: 'wander', alt: "Cave mouth silhouettes", sourcePage: '/' },
  { id: '067-dsc-6936-1', src: '/photos/web/067-dsc-6936-1.webp', thumb: '/photos/thumb/067-dsc-6936-1.webp', w: 1600, h: 1068, ar: 1.4981, category: 'branding', alt: "The antler bench", sourcePage: '/' },
  { id: '068-img-7310-2', src: '/photos/web/068-img-7310-2.webp', thumb: '/photos/thumb/068-img-7310-2.webp', w: 1068, h: 1600, ar: 0.6675, category: 'folks', alt: "Mid-laugh in magenta", sourcePage: '/' },
  { id: '069-img-2024', src: '/photos/web/069-img-2024.webp', thumb: '/photos/thumb/069-img-2024.webp', w: 1067, h: 1600, ar: 0.6669, category: 'folks', alt: "Lakeshore ceremony", sourcePage: '/lets-work-together' },
  { id: '070-dsc-8749', src: '/photos/web/070-dsc-8749.webp', thumb: '/photos/thumb/070-dsc-8749.webp', w: 1067, h: 1600, ar: 0.6669, category: 'folks', alt: "Golden hour cowboy", sourcePage: '/lets-work-together' },
  { id: '071-dsc-9676', src: '/photos/web/071-dsc-9676.webp', thumb: '/photos/thumb/071-dsc-9676.webp', w: 1068, h: 1600, ar: 0.6675, category: 'folks', alt: "Boots on the bumper", sourcePage: '/lets-work-together' },
  { id: '072-img-7284', src: '/photos/web/072-img-7284.webp', thumb: '/photos/thumb/072-img-7284.webp', w: 1386, h: 1600, ar: 0.8662, category: 'folks', alt: "Ashley, a lamb, and a camera", sourcePage: '/about' },
  { id: '073-dsc-6462', src: '/photos/web/073-dsc-6462.webp', thumb: '/photos/thumb/073-dsc-6462.webp', w: 1600, h: 1067, ar: 1.4995, category: 'wander', alt: "Train table for two", sourcePage: '/new-page' },
  { id: '074-dsc-6345', src: '/photos/web/074-dsc-6345.webp', thumb: '/photos/thumb/074-dsc-6345.webp', w: 1600, h: 1067, ar: 1.4995, category: 'wander', alt: "Trench coat by the window", sourcePage: '/new-page' },
  { id: '075-dsc-4585', src: '/photos/web/075-dsc-4585.webp', thumb: '/photos/thumb/075-dsc-4585.webp', w: 1600, h: 1372, ar: 1.1662, category: 'wander', alt: "Taped hands, lit cigarette", sourcePage: '/new-page' },
  { id: '076-dsc-5719', src: '/photos/web/076-dsc-5719.webp', thumb: '/photos/thumb/076-dsc-5719.webp', w: 1570, h: 1600, ar: 0.9812, category: 'wild', alt: "Resting on the saddle pile", sourcePage: '/new-page' },
  { id: '077-dsc-6241', src: '/photos/web/077-dsc-6241.webp', thumb: '/photos/thumb/077-dsc-6241.webp', w: 1225, h: 1600, ar: 0.7656, category: 'wander', alt: "Peter Rabbit, on loan", sourcePage: '/new-page' },
  { id: '078-img-2541-2', src: '/photos/web/078-img-2541-2.webp', thumb: '/photos/thumb/078-img-2541-2.webp', w: 1600, h: 1068, ar: 1.4981, category: 'folks', alt: "UFO mug, lunch break", sourcePage: '/contact-3' },
]

export const categoryLabels: Record<PhotoCategory, string> = {
  folks: 'Folks',
  branding: 'Branding',
  wild: 'The Wild',
  wander: 'Wanderings',
}
